name: social_photo_album
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.20.1
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.7.0

  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # **Замість cloud_firestore_mocks використовуємо fake_cloud_firestore**
  fake_cloud_firestore: ^2.5.2

  # Пакети для фото
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.0

  # Google Sign-In
  google_sign_in: ^6.1.2
  path: ^1.8.3

  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

  hive_generator: ^2.0.0
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
