// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHlto0OKbsrQjOadZMDVYQUFsqec7VSQ',
    appId: '1:645034820770:web:c06842381aadae818e43fb',
    messagingSenderId: '645034820770',
    projectId: 'social-photo-album',
    authDomain: 'social-photo-album.firebaseapp.com',
    storageBucket: 'social-photo-album.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCpeqNA0Xo3S3a0OFU-7yRtIq3BXBdQI',
    appId: '1:645034820770:android:2a09613b5482b40d8e43fb',
    messagingSenderId: '645034820770',
    projectId: 'social-photo-album',
    storageBucket: 'social-photo-album.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3G3OEc2CnfiZ04l-LxfIil2-qG_po38U',
    appId: '1:645034820770:ios:2d623deaed9e49098e43fb',
    messagingSenderId: '645034820770',
    projectId: 'social-photo-album',
    storageBucket: 'social-photo-album.firebasestorage.app',
    iosClientId: '645034820770-eb6bf3qoopkpte931fnp427tqipvgohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialPhotoAlbum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3G3OEc2CnfiZ04l-LxfIil2-qG_po38U',
    appId: '1:645034820770:ios:2d623deaed9e49098e43fb',
    messagingSenderId: '645034820770',
    projectId: 'social-photo-album',
    storageBucket: 'social-photo-album.firebasestorage.app',
    iosClientId: '645034820770-eb6bf3qoopkpte931fnp427tqipvgohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialPhotoAlbum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIHlto0OKbsrQjOadZMDVYQUFsqec7VSQ',
    appId: '1:645034820770:web:8abf0058b5ab87aa8e43fb',
    messagingSenderId: '645034820770',
    projectId: 'social-photo-album',
    authDomain: 'social-photo-album.firebaseapp.com',
    storageBucket: 'social-photo-album.firebasestorage.app',
  );

}